openapi: "3.0.0"
info:
  version: 1.0.0
  title: HomeNet
  description: Listings of properties for sale
  license:
    name: MIT
servers:
- url: http://localhost:3000
paths:
  /listings:
    get:
      summary: List all listings
      operationId: listListings
      tags:
      - listings
      parameters:
      - name: municipality
        in: query
        description: filter by municipality
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Array of listings
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseListings"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new listing
      operationId: createListing
      tags:
      - listings
      requestBody:
        description: The listing to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '201':
          description: Created listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseListing"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /listings/{id}:
    get:
      summary: List a listing
      operationId: listListing
      tags:
      - listings
      parameters:
      - name: id
        in: path
        description: listingId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Returned listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseListing"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Edit a listing
      operationId: editListing
      tags:
      - listings
      parameters:
      - name: id
        in: path
        description: listingId
        required: true
        schema:
          type: string
      requestBody:
        description: The listing to edit
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '200':
          description: Edited listing
        '201':
          description: Created listing
        '204':
          description: Nothing happened
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete listing
      operationId: deleteListing
      tags:
      - listings
      parameters:
      - name: id
        in: path
        description: listingId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Deleted listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseListing"
        '204':
          description: Nothing happened
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Listing:
      type: object
      properties:
        coords:
          type: object
          properties:
            lat:
              type: number
            lng:
              type: number
        street:
          type: object
          properties:
            name:
              type: string
            number:
              type: number
        municipality:
          type: string
        type:
          type: string
        price:
          type: number
        fee:
          type: number
        bidding:
          type: boolean
    ResponseListing:
      allOf:
      - $ref: "#/components/schemas/Listing"
      - properties:
          __v:
            type: integer
            format: uint32
          _id:
            type: string
            format: uuid
    ResponseListings:
      type: array
      items:
        $ref: "#/components/schemas/ResponseListing"
    Error:
      required:
        - error
      properties:
        error:
          type: object
          properties:
            expose:
              type: boolean
            statusCode:
              type: integer
              format: uint32
            status:
              type: integer
              format: uint32
            body:
              title: body as escaped json
              type: string
            type:
              title: fault desciption
              type: string
